# Generated by Django 5.0 on 2023-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='yosofasady2@gmial.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
