# Generated by Django 5.0 on 2023-12-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodTagModel',
        ),
    ]
