# Generated by Django 5.0 on 2023-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
