# Generated by Django 5.0 on 2023-12-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_old_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(null=True),
        ),
    ]
