# Generated by Django 5.0 on 2023-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_old_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='row_id',
            field=models.TextField(),
        ),
    ]
