# Generated by Django 5.0 on 2023-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
