# Generated by Django 5.0 on 2023-12-20 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0002_remove_food_picture_url_food_category_food_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodmenu.category'),
        ),
    ]
