# Generated by Django 5.0 on 2023-12-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0004_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='idd',
        ),
    ]
