# Generated by Django 5.0 on 2023-12-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0005_rename_id_category_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='idd',
            new_name='id',
        ),
    ]
