# Generated by Django 5.0 on 2023-12-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0010_alter_food_foodimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='foodimage',
        ),
    ]
