# Generated by Django 5.0 on 2023-12-18 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('R', 'reserved'), ('E', 'empty'), ('F', 'full')], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'accept'), ('D', 'Denied'), ('O', 'on_process')], default='O', max_length=1)),
                ('phone_number', models.CharField(max_length=11)),
                ('number_of_persons', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField()),
                ('table', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
            ],
        ),
    ]
