# Generated by Django 5.0 on 2024-01-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('A', 'Accept'), ('D', 'Denied'), ('O', 'On_Process')], default='O', max_length=1),
        ),
    ]
