# Generated by Django 5.0 on 2023-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('P', 'Preparation'), ('T', 'Transmission'), ('F', 'Finished')], default='W', max_length=1),
        ),
    ]
